apiVersion: v1
kind: Service
metadata:
  name: simple-nginx-service
  annotations:
    # Optional but good for GKE: ensure only L4 Load Balancer is created
    cloud.google.com/load-balancer-type: "Internal" 
spec:
  # VITAL CHANGE: Ensures the Load Balancer only targets nodes where the pods exist.
  externalTrafficPolicy: Local 
  
  selector:
    app: simple-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
