apiVersion: v1
kind: Service
metadata:
  name: simple-nginx-service
  #annotations:
    # VITAL CHANGE: Use the GKE Regional Backend Service (RBS) architecture.
    # This architecture uses Network Endpoint Groups (NEGs) as backends, 
    # ensuring only Pods (and thus only the nodes running them) are targeted,
    # thereby excluding the default-pool nodes from the backend list.
    #cloud.google.com/l4-rbs: "enabled"
spec:
  # externalTrafficPolicy: Local is technically redundant with L4-RBS enabled
  # but can be left for additional enforcement if desired.
  #externalTrafficPolicy: Local 
  
  selector:
    app: simple-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
